[package]
name = "portal-pc-koffle"
version = "0.0.1"
edition = "2021"
license = "CC0-1.0"
description = "Krazy things with WAFFLE"

[dependencies]
anyhow = "1.0.95"
once_map = "0.4.21"
portal-pc-waffle = "0.3.8"
waffle-ast = "0.4.3"

[features]
corpack=[]
